### ISSUE TITLE
Update package.json and push to npm

### ISSUE THREAD

**Issue by cyraxx** [SpencerSharkey/node-pogo-signature#10]
Could you update the version number in `package.json` and push that release to npm so that I can switch pogobuf back to the npm package?

BTW, with the merge from starkevin's repo into this one you also updated the `package.json` to point at starkevin's repo even though it is now in SpencerSharkey's repo again. You'll probably want to change that back so the npm to GitHub links will be correct.

**Comment by SpencerSharkey** [comment]
Will get to this in a bit, thanks for reminding me... been busy with a few things lately.

Node pogo will live on!

**Comment by SpencerSharkey** [comment]
Published, good to go now!

3.0.0 is available!

**Comment by cyraxx** [comment]
Switched pogobuf back to the npm package, thanks!
