### ISSUE TITLE
npm permissions

### ISSUE THREAD

**Issue by niicojs** [SpencerSharkey/node-pogo-signature#14]
As this repo is way outdated, could you please give permissions on npm to both @starkevin and @cyraxx so we can publish an update?
thanks

**Comment by cyraxx** [comment]
I don't really need them to be honest, but it would be great if @starkevin would be able to push to npm.
Currently I'm simply pointing pogobuf at at his repo and I'd much prefer being able to use actual npm versions.

**Comment by niicojs** [comment]
Did you have a look @SpencerSharkey?

**Comment by SpencerSharkey** [comment]
Sorry about the delay, didn't see this in my inbox till just today.

I attempted to add @starkevin to the NPM repo but he does not have an account there. In lieu of this, I've added @cyraxx. 

If you're up to the task of maintaining the NPM repo I'd be glad to add you too, @nicoschmitt

**Comment by starkevin** [comment]
@SpencerSharkey it's StarKevin

**Comment by SpencerSharkey** [comment]
user not found: StarKevin

![image](https://cloud.githubusercontent.com/assets/4871369/25156540/29cdf588-2469-11e7-84fa-b49e2de77afa.png)
