### ISSUE TITLE
ES6?

### ISSUE THREAD

**Issue by st0ffern** [SpencerSharkey/node-pogo-signature#3]
Change callbacks to promises + additional snack?

**Comment by SpencerSharkey** [comment]
what is an additional snack?

**Comment by st0ffern** [comment]
- async functions
- for-in
- arrow functions
- block scoping
- classes
- computed properties
- template litterals

easier syntaxes to read :smile:

**Comment by SpencerSharkey** [comment]
yes, i started a bit of work

your repo gone?

**Comment by st0ffern** [comment]
@SpencerSharkey i got a C&D :disappointed:
