### ISSUE TITLE
handle requests pre-auth_ticket

### ISSUE THREAD

**Issue by SpencerSharkey** [SpencerSharkey/node-pogo-signature#4]
originally discussed here: https://github.com/keyphact/pgoapi/pull/74

node-pogo-signature should handle this logic.
will figure out best way to implement, unless anyone has some ideas.

**Comment by vankxr** [comment]
It works the same way.
Pass a buffer with `auto_info` encoded instead of `auto_ticket` and it will sign successfully.

(Be Sure to Give ticket signing priority, always sign with ticket if a valid one is available)

**Comment by starkevin** [comment]
This has instead been implemented at the API level - Passing auth_info in works fine
